### ISSUE TITLE
res.message.user.id contains room id in groups

### ISSUE THREAD

**Issue by Kiina** [puresmash/hubot-line-messaging#2]
So if you send the bot a private message, res.message.user.id contains the ID from the User (starting with U). If you add him to a group and send a message, it contains the Room ID (starting with R). So there is no way to differentiate users in a chat room and "room" is always undefined, even in chats from a group.
Also user.id and user.name is the same. Not sure if that is supposed to be.

**Comment by puresmash** [comment]
Hi Kiina,

Thanks for the questions. Refer to your first question, I would say I am also confused about it when I first developed these parts. There is an info on Line's official api document: 

> You cannot get the user IDs of individual users in a room.

I don't know why they make this decision, but it does restrict the applicability of their chatting robot.

About your second question. Line do not provide username even in a private message, but they do provide another api to get some simple user profile. Thanks for your suggestion, I will offer a correct `user.name ` and a customized switch to open this feature at version 0.6.0.

**Comment by Kiina** [comment]
So no way to assign messages to a user in a group? That's a bummer, maybe it gets changed in the future.

Is the api to get the user profile the same as the one that requires app authorization? When you add my bot you have to confirm that it has permissions to your profile picture. I have seen other bots without this but found no way to change it on the line site, maybe you know where it is. Otherwise it would be cool to be able to read more information about the user.

**Comment by puresmash** [comment]
So that is why Line ask us for personal profile permissions when we first add the bot to friend list. I almost forgot.

I will include simple personal profile at next version, but you still can access these user profiles by [this API](https://devdocs.line.me/en/#bot-api-get-profile).

**Comment by puresmash** [comment]
I have pushed this feature in v0.6.0.

**Comment by Kiina** [comment]
Works great
